name: Deploy to Staging

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Add VPS to known_hosts
        run: ssh-keyscan -H ${{ secrets.STAG_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Staging Server
        run: |
          ssh ${{ secrets.STAG_USER }}@${{ secrets.STAG_HOST }} "
            cd ${{ secrets.STAG_DIR }} &&
            git pull origin dev &&
            composer install --no-dev --optimize-autoloader &&
            php artisan migrate &&
            php artisan optimize:clear &&
            php artisan optimize
          "
